# Generated by Django 4.1 on 2022-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Polls Question',
                'verbose_name_plural': 'Polls questions',
                'ordering': ['pk'],
            },
        ),
    ]
