# Generated by Django 4.1 on 2022-09-16 22:08

from django.db import migrations, models
import todo.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['is_important'],
            },
            bases=(models.Model, todo.mixin.DateTimeMixin),
        ),
    ]
